apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-argocd-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: riya299/jenkins-argocd-demo:6
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-argocd-demo-svc
spec:
  selector:
    app: demo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30366  
  type: NodePort
